<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class mm_nota_email extends CI_Model {

	function __construct()
	{
		parent::__construct();
	}
	
	function get_approval($no_surat, $hal, $penyusun)
	{
		$base_url = base_url();
		$message = <<<EOD
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Dengan hormat,</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Berikut permohonan persetujuan Nota Dinas :</span></p>
<table style="padding: 0px; display: table; border-collapse: collapse; word-break: break-word; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; border: none;" border="1" cellspacing="0" cellpadding="0">
<tbody style="width: 575px;">
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: solid none solid solid; border-top-color: #4f81bd; border-bottom-color: #4f81bd; border-left-color: #4f81bd; border-top-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Nomor Nota Dinas</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: solid solid solid none; border-top-color: #4f81bd; border-right-color: #4f81bd; border-bottom-color: #4f81bd; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><span style="font-size: 8pt;">$no_surat</span></p>
</td>
</tr>
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: none none solid solid; border-left-color: #4f81bd; border-left-width: 1pt; border-bottom-color: #4f81bd; border-bottom-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Hal</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: none solid solid none; border-bottom-color: #4f81bd; border-bottom-width: 1pt; border-right-color: #4f81bd; border-right-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">$hal</span></strong></p>
</td>
</tr>
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: none none solid solid; border-left-color: #4f81bd; border-left-width: 1pt; border-bottom-color: #4f81bd; border-bottom-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Penyusun</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: none solid solid none; border-bottom-color: #4f81bd; border-bottom-width: 1pt; border-right-color: #4f81bd; border-right-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><span style="font-size: 8pt;">$penyusun</span></p>
</td>
</tr>
</tbody>
</table>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">yang memerlukan persetujuan anda.</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Silahkan klik link berikut untuk melihat detail Nota Dinas &amp; melakukan persetujuan :</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;"><a style="text-decoration: underline; margin: 0px; padding: 0px; background-color: rgba(0, 0, 0, 0); color: purple; outline: none; background-position: initial initial; background-repeat: initial initial;" href="$base_url" target="_blank" rel="nofollow" shape="rect">link aplikasi</a></span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;">&nbsp;</span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Atas perhatiannya kami ucapkan terimakasih.</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><em><span style="font-size: 8pt;">*Email ini digenerate otomatis oleh system</span></em></p>
EOD;
		
		return $message;
	}

	function get_revisi($no_surat, $hal, $penyusun)
	{
		$base_url = base_url();
		$message = <<<EOD
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Dengan hormat,</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Berikut permohonan revisi Nota Dinas :</span></p>
<table style="padding: 0px; display: table; border-collapse: collapse; word-break: break-word; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; border: none;" border="1" cellspacing="0" cellpadding="0">
<tbody style="width: 575px;">
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: solid none solid solid; border-top-color: #4f81bd; border-bottom-color: #4f81bd; border-left-color: #4f81bd; border-top-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Nomor Nota Dinas</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: solid solid solid none; border-top-color: #4f81bd; border-right-color: #4f81bd; border-bottom-color: #4f81bd; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><span style="font-size: 8pt;">$no_surat</span></p>
</td>
</tr>
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: none none solid solid; border-left-color: #4f81bd; border-left-width: 1pt; border-bottom-color: #4f81bd; border-bottom-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Hal</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: none solid solid none; border-bottom-color: #4f81bd; border-bottom-width: 1pt; border-right-color: #4f81bd; border-right-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">$hal</span></strong></p>
</td>
</tr>
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: none none solid solid; border-left-color: #4f81bd; border-left-width: 1pt; border-bottom-color: #4f81bd; border-bottom-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Penyusun</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: none solid solid none; border-bottom-color: #4f81bd; border-bottom-width: 1pt; border-right-color: #4f81bd; border-right-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><span style="font-size: 8pt;">$penyusun</span></p>
</td>
</tr>
</tbody>
</table>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Silahkan klik link berikut untuk melihat detail revisi :</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;"><a style="text-decoration: underline; margin: 0px; padding: 0px; background-color: rgba(0, 0, 0, 0); color: purple; outline: none; background-position: initial initial; background-repeat: initial initial;" href="$base_url" target="_blank" rel="nofollow" shape="rect">link aplikasi</a></span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;">&nbsp;</span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Atas perhatiannya kami ucapkan terimakasih.</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><em><span style="font-size: 8pt;">*Email ini digenerate otomatis oleh system</span></em></p>
EOD;
		
		return $message;
	}
	
	function get_selesai($no_surat, $hal, $penyusun)
	{
		$base_url = base_url();
		$message = <<<EOD
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Dengan hormat,</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Dengan ini diberitahukan, bahwa Nota Dinas :</span></p>
<table style="padding: 0px; display: table; border-collapse: collapse; word-break: break-word; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; border: none;" border="1" cellspacing="0" cellpadding="0">
<tbody style="width: 575px;">
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: solid none solid solid; border-top-color: #4f81bd; border-bottom-color: #4f81bd; border-left-color: #4f81bd; border-top-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Nomor Nota Dinas</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: solid solid solid none; border-top-color: #4f81bd; border-right-color: #4f81bd; border-bottom-color: #4f81bd; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><span style="font-size: 8pt;">$no_surat</span></p>
</td>
</tr>
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: none none solid solid; border-left-color: #4f81bd; border-left-width: 1pt; border-bottom-color: #4f81bd; border-bottom-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Hal</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: none solid solid none; border-bottom-color: #4f81bd; border-bottom-width: 1pt; border-right-color: #4f81bd; border-right-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">$hal</span></strong></p>
</td>
</tr>
<tr style="display: table-row; vertical-align: inherit; min-height: 0.2in;">
<td style="display: table-cell; border-spacing: 2px; width: 99pt; border-style: none none solid solid; border-left-color: #4f81bd; border-left-width: 1pt; border-bottom-color: #4f81bd; border-bottom-width: 1pt; background-color: #c6d9f1; padding: 0in 5.4pt; min-height: 0.2in; background-position: initial initial; background-repeat: initial initial;" colspan="1" rowspan="1" width="132">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><strong><span style="font-size: 8pt;">Penyusun</span></strong></p>
</td>
<td style="display: table-cell; border-spacing: 2px; width: 310.1pt; border-style: none solid solid none; border-bottom-color: #4f81bd; border-bottom-width: 1pt; border-right-color: #4f81bd; border-right-width: 1pt; padding: 0in 5.4pt; min-height: 0.2in;" colspan="1" rowspan="1" width="413">
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt;"><span style="font-size: 8pt;">$penyusun</span></p>
</td>
</tr>
</tbody>
</table>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">telah selesai proses approval.</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Silahkan klik link berikut untuk melihat detail Nota Dinas :</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;"><a style="text-decoration: underline; margin: 0px; padding: 0px; background-color: rgba(0, 0, 0, 0); color: purple; outline: none; background-position: initial initial; background-repeat: initial initial;" href="$base_url" target="_blank" rel="nofollow" shape="rect">link aplikasi</a></span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;">&nbsp;</span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Atas perhatiannya kami ucapkan terimakasih.</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><em><span style="font-size: 8pt;">*Email ini digenerate otomatis oleh system</span></em></p>
EOD;
		
		return $message;
	}
	
	function get_broadcast($no_surat, $hal)
	{
		$message = <<<EOD
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Dengan hormat,</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Bersama ini kami lampirkan Nota Dinas :</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;">No.<span class="Apple-converted-space">&nbsp;</span><a style="text-decoration: underline; margin: 0px; padding: 0px; background-color: rgba(0, 0, 0, 0); color: purple; outline: none; background-position: initial initial; background-repeat: initial initial;" href="detail/186" target="_blank" rel="nofollow" shape="rect"><span style="color: windowtext; text-decoration: none;">$no_surat</span></a></span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><strong><span style="font-size: 10pt;">Perihal &ldquo;$hal&rdquo;</span></strong></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Mohon dapat diterima dengan baik.</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">Demikian Nota Dinas ini kami sampaikan, atas perhatiannya kami ucapkan terimakasih.</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><span style="font-size: 10pt;">&nbsp;</span></p>
<p style="padding: 0px; margin: 0px 0in; display: block; font-size: 12pt; color: #000000; font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, Arial, 'Lucida Grande', sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff;"><em><span style="font-size: 8pt;">*Email ini digenerate otomatis oleh system</span></em></p>
EOD;
		
		return $message;
	}
}